apiVersion: v1
kind: Service
metadata:
  name: {{ include "gataria-backend-images.fullname" . }}
  labels:
    {{- include "gataria-backend-images.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.NodePort }}
  ports:
    - port: {{ .Values.service.targetPort }}
      targetPort: http
      protocol: TCP
      name: http
      NodePort: {{ .Values.service.NodePort }}
  selector:
    {{- include "gataria-backend-images.selectorLabels" . | nindent 4 }}
